#if !defined(AFX_SKYTAX_H__E155CA59_98B1_4A5D_B806_3A5E34D1FE91__INCLUDED_)
#define AFX_SKYTAX_H__E155CA59_98B1_4A5D_B806_3A5E34D1FE91__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSkytAX wrapper class

class CSkytAX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSkytAX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4cd5b214, 0xebf, 0x4e87, { 0xbe, 0x89, 0x48, 0x22, 0xdd, 0x11, 0x8f, 0xbc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long pOpenCom(LPCTSTR m_Com, long m_Pt);
	long pQdStrG(long n, LPCTSTR StrG);
	CString retStr(long n);
	long pCall(long n, long* pInt);
	double GetXyz(short n);
	double GetMcDL(short n);
	short GetHzt(short n);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SKYTAX_H__E155CA59_98B1_4A5D_B806_3A5E34D1FE91__INCLUDED_)
